### ISSUE TITLE
all day events display incorrectly

### ISSUE THREAD

**Issue by patriciacrain** [salesforce-experiencecloud/EventsCalendar#1]
Having an issue with all day events displaying on the calendar. The Calendar Event Details correctly show the Start Date and End Date on the Event, but when displayed on the calendar it shows as one day less than the End Date. So if the Event is July 21 to July 23 it will display only on July 21 and July 22. This is true in all the views (Month, Week, Day, List).
<img width="445" alt="Screen Shot 2022-07-07 at 12 35 08 PM" src="https://user-images.githubusercontent.com/6697146/177814194-bef15a5d-af38-4040-a1f6-6a93f0c4d7d9.png">
<img width="627" alt="Screen Shot 2022-07-07 at 12 35 03 PM" src="https://user-images.githubusercontent.com/6697146/177814201-177c44ab-492f-4e3b-927b-942abc2c6435.png">
<img width="883" alt="Screen Shot 2022-07-07 at 12 34 48 PM" src="https://user-images.githubusercontent.com/6697146/177814202-45077078-5385-4572-8c67-c7fda33e7c1b.png">

**Comment by gtabboud** [comment]
Is the timezone of the user who created the event and the timezone being selected on the calendar page the same?

**Comment by patriciacrain** [comment]
The timezone of the user who created the event is (GMT-03:00) Atlantic Daylight Time (America/Moncton). The timezone selected on the calendar page shows as "Local - America/Moncton.

**Comment by gtabboud** [comment]
hmm interesting...so it's the same timezone of the user who created the event, and the viewing user. right?

**Comment by gtabboud** [comment]
might you have credentials for me to be able to login to the site as that viewing user and debug, that you can share?

**Comment by patriciacrain** [comment]
From what I can tell, yes. But when I switch the calendar to Etc/GMT-3 (which is theoretically the same offset as the user), it shifts the event so rather than showing July 21-22 (in error), it shows July 22-23. It's like it doesn't recognize the third day of the event at all.

**Comment by patriciacrain** [comment]
If I go into "Grant Account Login Access" and enable access for "Salesforce Labs Business Org (LBO) Support" will that work?

**Comment by gtabboud** [comment]
I don't believe that will work...if you use slack, would you be up for joining this workspace / community? https://join.slack.com/t/salesforceohana/shared_invite/zt-1bnseg71x-QF8ohUD9VXReis_kI9mlug

and we can chat more privately there for sharing credentials and such...

**Comment by gtabboud** [comment]
Thanks for reaching out about this and working with me on a solution / testing @patriciacrain ! The latest packaged version (v1.18 - https://login.salesforce.com/packaging/installPackage.apexp?p0=04t3h000004pNbK) and this commit: https://github.com/salesforce-experiencecloud/EventsCalendar/commit/c7dc5cc0f0c5763e391dc5d28c1d01aa816697a2 fix the all day issue you describe in this thread.

Based on that, I'll close this issue. Thanks again!
