### ISSUE TITLE
Package enhancement

### ISSUE THREAD

**Issue by sybrendb1** [salesforce-experiencecloud/EventsCalendar#2]
Hi @gtabboud, 

We are very positive about your package.
We would like to use your package for our experience cloud site. 
But for that, we need some extra features. 
We will list our features(Must have, nice to have & future must have) up in separate enhancement tickets.
Are you prepared to add those features? 
This would be very helpful to us.
We were also wondering what your roadmap looks like. 
Which features would you like to add to your package or is this the final?

**Comment by gtabboud** [comment]
Thank you for your feedback. Right now there are no plans to make significant enhancements to the package, but I will keep your suggestions if in the future that changes. 

However, the package is open-sourced so you can definitely clone the repo and make the enhancements you wish.
