### ISSUE TITLE
Feature: translation workbench

### ISSUE THREAD

**Issue by sybrendb1** [salesforce-experiencecloud/EventsCalendar#3]
**Must have feature**
For the title and description, we would like to be able to use the translation workbench so that the language in the calendar changes with the language chosen in the settings.

**Comment by gtabboud** [comment]
Not planned, will consider for future.

**Comment by gtabboud** [comment]
I actually think that this won't be possible because of how the platform works. Titles and Descriptions come from event fields, which are considered data, and are not translatable from the translation workbench.
